# build environment
FROM node:12.18.1
WORKDIR /app/client
ENV PATH /app/client/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm ci -qy
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

COPY . .

EXPOSE 3000

CMD [ "npm","start" ]